# -*- coding:utf-8 -*-

# <SUBID:16356367,UPDATE:20230205>
# English:
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde" Output: "e" Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y" Output: "y"
# Constraints:
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
#
# 中文:
# 给定两个字符串 s 和 t ，它们只包含小写字母。
# 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。
# 请找出在 t 中被添加的字母。
# 示例 1：
# 输入：s = "abcd", t = "abcde" 输出："e" 解释：'e' 是那个被添加的字母。
# 示例 2：
# 输入：s = "", t = "y" 输出："y"
# 提示：
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s 和 t 只包含小写字母


#
# @lc app=leetcode.cn id=389 lang=python
#
# [389] 找不同
#
# https://leetcode-cn.com/problems/find-the-difference/description/
#
# algorithms
# Easy (54.07%)
# Total Accepted:    7.7K
# Total Submissions: 13.9K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 给定两个字符串 s 和 t，它们只包含小写字母。
#
# 字符串 t 由字符串 s 随机重排，然后在随机位置添加一个字母。
#
# 请找出在 t 中被添加的字母。
#
#
#
# 示例:
#
# 输入：
# s = "abcd"
# t = "abcde"
#
# 输出：
# e
#
# 解释：
# 'e' 是那个被添加的字母。
#
#
#
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        tmp = 0
        for i in (s + t):
            tmp ^= ord(i)
        return chr(tmp)

if __name__ == "__main__":
    s = Solution().findTheDifference('abcd', 'acbed')


